---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    name: demo
spec:
  type: NodePort
  ports:
  - port: 8092
    targetPort: 8092
    protocol: TCP
    nodePort: 32143
  selector:
    app: demo
