apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    name: demo
spec:
  selector:
    matchLabels:
      name: demo
  template:
    metadata:
      labels:
        name: demo
    spec:
      containers:
        - name: demo
          image: 10.0.4.8:5000/demo:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090